### ISSUE TITLE
網站上面沒有 Debian 相關訊息

### ISSUE THREAD

**Issue by fourdollars** [linux-taiwan/linux-taiwan.github.io#3]

**Comment by kidwm** [comment]
我們有 http://debian.linux.org.tw/ 但是是鏡像站，不是社群站啊

**Comment by fourdollars** [comment]
我覺得可以生一個 http://www.linux.org.tw/debian/ 來維護也不錯。

**Comment by szlin** [comment]
可以協助生出Debian 社群站, 讓Debian愛好者能有個地方交流.
屆時再看要將 http://debian.linux.org.tw/  導回社群站或者使用新URL.

**Comment by kidwm** [comment]
@szlin 你願意參與這個任務嗎？我可以開好 repo 把權限給你。
@fourdollars 還是去詢問 Andrew 把鏡像站搬到 http://mirror.linux.org.tw/ 的可能性？

**Comment by szlin** [comment]
@kidwm 願意全力協助. 使用Debian多年, 也應該為他盡點力.

**Comment by fourdollars** [comment]
@kidwm @szlin 私底下寫信給我說想要幫忙 Debian，所以我就將他引導到這裡了。
目前 http://debian.linux.org.tw 不建議改動，應該有太多的地方都在用 http://debian.linux.org.tw ，我個人覺得目前比較方便的變通方式是直接維護一個 http://www.linux.org.tw/debian/ 目錄。

**Comment by kidwm** [comment]
@szlin Repo 和權限都開好囉，Jekyll 的使用可以參考 fedora.linux.org.tw。
@fourdollars 怎麼可以讓 debian 矮一截勒，如果先改 ubuntu 和 debian 的鏡像指向到 mirror.linux.org.tw, 過一陣子再來更換內容應該可行，還是直接問問 Andrew 的意見？

**Comment by szlin** [comment]
@kidwm 謝謝. 會想一下內容, 討論後再進行更新.

**Comment by fourdollars** [comment]
@kidwm 是的，我不是 debian.linux.org.tw 的管理員，所以跟我談沒有用。

**Comment by fourdollars** [comment]
我的建議是直接開幹 http://www.linux.org.tw/debian/ ，等以後真的可以用 http://debian.linux.org.tw 時再搬過去也是可行。

**Comment by fourdollars** [comment]
剛剛跟 Andrew 還有 @kidwm 討論了一下，多出了兩個新的選擇 http://www.debian.org.tw 或是 http://www.debian.tw ，不過我還是覺得可以先弄 http://www.linux.org.tw/debian/ 同時也聯繫 http://www.debian.org.tw 或是 http://www.debian.tw 的維護者。

**Comment by kidwm** [comment]
@chihchun 您願意釋出 debian.org.tw 回來給社群重新運用嗎？

**Comment by chihchun** [comment]
## 1. 關於 mirror site

不理解把 ftp.tw.debian.org 搬到 mirror.linux.org.tw 的用意，是想改變網域名稱還是創建一個新的 archive 伺服器。我個人不支持純粹自我感覺良好改網址，而非替社群創造新的服務。

ftp.tw.debian.org 目前指向 debian.linux.org.tw ，ftp.tw.debian.org 上游是 ftp-master.debian.org，下游有六個站。mirror.linux.org.tw 還有空間資源的話，可以成為 ftp.tw.debian.org (debian.linux.org.tw) 下游。

```
$ host ftp.tw.debian.org
ftp.tw.debian.org is an alias for debian.linux.org.tw.
debian.linux.org.tw has address 140.112.8.139
```
- Debian Mirror Checker http://mirror.debian.org/status.html

```
ftp-master.debian.org (392)
    ftp.tw.debian.org (8)
        debian.telsatbb.vu
        ftp.tku.edu.tw
        ftp.debianclub.org
        ftp.th.debian.org (4)
            mirror.kku.ac.th
            mirror.applebred.net
```

## 2. debian.org.tw 與 debian.tw 網域

debian.org.tw 是 Andrew Lee 擁有 (後續這幾年由我繳費維持)， debian.tw 是 Jack Liu 擁有。
我跟 @jessesung 有實質管理權，可以變動 dns record. 

```
$ whois debian.tw    
Domain Name: debian.tw
   Contact:
      Jack Liu
      chuany@ms6.hinet.net
   Record expires on 2017-08-20 (YYYY-MM-DD)
   Record created on 2009-08-19 (YYYY-MM-DD)
Registration Service Provider: PCHOME
```

```
$ whois debian.org.tw   
Domain Name: debian.org.tw
Registrant:
台灣蠻野心足生態協會
Wild at Heart Leagal
13F., No.86, Sec. 1, Chongcing S. Rd., Jhongjheng District, Taipei 100 (R.O.C.)

   Contact:
      Andrew Lee   andrew@linux.org.tw
      TEL:  02-23112345#505
      FAX:  02-23112688

   Record expires on 2016-06-04 (YYYY-MM-DD)
   Record created on 2003-06-04 (YYYY-MM-DD)

   Domain servers in listed order:
      ns1.nutsfactory.net       218.161.0.222 
      ns2.nutsfactory.net       218.161.0.222 

Registration Service Provider: SEEDNET
```

## 3. 新社群網站

目前 www.debian.tw 指向 http://moto.debian.tw, 為舊有討論區。 www.debian.org.tw 指向 wiki.debian.org.tw 但長年未有人更新資料，伺服器也年久失修。

你不需要問誰的意見才能經營新的 Debian 論壇或網站。請著手尋找伺服器資源動工吧，有了新 IP 位址，請告知我，我可以把 www.debian.org.tw 指過去。其他的需求也可以討論後，我直接把設定能力開放。

為了方便確認與聯繫，請 @szlin, @kidwm  與 @fourdollars 交換 PGP key, 以便後續可以安全的進行伺服器設定等溝通細節。

**Comment by fourdollars** [comment]
@chihchun 我們目前只是打算藉由 GitHub 來維護一個靜態網頁而已，像是 www.linux.org.tw 目前是放在 https://github.com/linux-taiwan/www.linux.org.tw 來維護。

**Comment by chihchun** [comment]
@fourdollars 請告知 IP 或 CNAME 位址，我會把 www.debian.org.tw 指配過去

**Comment by kidwm** [comment]
@chihchun 感謝，麻煩 CNAME 到 `linux-taiwan.github.io`

**Comment by chihchun** [comment]
done

# cname to linux-taiwan.github.io.

```
$ host -va www.debian.org.tw zion.debian.org.tw.
Trying "www.debian.org.tw"
Using domain server:
Name: zion.debian.org.tw.
Address: 218.161.0.222#53
Aliases: 

;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 25941
;; flags: qr aa rd; QUERY: 1, ANSWER: 1, AUTHORITY: 4, ADDITIONAL: 1

;; QUESTION SECTION:
;www.debian.org.tw.     IN  ANY

;; ANSWER SECTION:
www.debian.org.tw.  43200   IN  CNAME   linux-taiwan.github.io.

;; AUTHORITY SECTION:
debian.org.tw.      43200   IN  NS  nutsfactory.net.
debian.org.tw.      43200   IN  NS  kalug.linux.org.tw.
debian.org.tw.      43200   IN  NS  cola.voip.idv.tw.
debian.org.tw.      43200   IN  NS  linux3.cc.ntu.edu.tw.

;; ADDITIONAL SECTION:
nutsfactory.net.    604800  IN  A   218.161.0.222
```

# redirect debian.org.tw to www.debian.org.tw

```
$ curl -H 'Pragma: no-cache' -v http://debian.org.tw
* Rebuilt URL to: http://debian.org.tw/
* Hostname was NOT found in DNS cache
*   Trying 218.161.0.222...
* Connected to debian.org.tw (218.161.0.222) port 80 (#0)
> GET / HTTP/1.1
> User-Agent: curl/7.38.0
> Host: debian.org.tw
> Accept: */*
> Pragma: no-cache
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 301 Moved Permanently
< Server: nginx/1.1.19
< Date: Thu, 21 Jan 2016 10:53:08 GMT
< Content-Type: text/html; charset=iso-8859-1
< Content-Length: 350
< Location: http://www.debian.org.tw/
< X-Cache: MISS from proxy.nutsfactory.net
< X-Cache-Lookup: MISS from proxy.nutsfactory.net:3128
< X-Cache: MISS from cardon.taipei
< X-Cache-Lookup: MISS from cardon.taipei:3128
< Via: 1.0 proxy.nutsfactory.net (squid/3.1.19), 1.0 cardon.taipei (squid/3.1.19)
* HTTP/1.0 connection set to keep alive!
< Connection: keep-alive
< 
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.debian.org.tw/">here</a>.</p>
<hr>
<address>Apache/2.2.9 (Debian) PHP/5.2.6-1+lenny16 with Suhosin-Patch Server at debian.org.tw Port 80</address>
</body></html>
* Connection #0 to host debian.org.tw left intact
```

**Comment by kidwm** [comment]
@chihchun Thank you!
