### ISSUE TITLE
Add preload linux desktop vendor

### ISSUE THREAD

**Issue by ycheng** [linux-taiwan/linux-taiwan.github.io#7]
我後來才發現台灣有一家公司, 有賣 pre-load linux 的 dell 筆電

我想那真是太棒了, 如果在我們網站上可以放他們連結似乎不錯

看了一下, 我大概可以寫出一個 MP 來加入, 但是不太確定如何在
local 把網站跑起來 verify

看了一下 http://jekyllrb.com/docs/ 似乎不行, 能給一些 comment 或是建議嗎?

ref: https://www.linuxyes.com/

**Comment by kidwm** [comment]
可以參考 GitHub Pages Ruby Gem 的說明 
https://github.com/github/pages-gem

**Comment by MGdesigner** [comment]
Hi 選我選我 請加我XD 這裡是 Musicha
品牌名 Musicha ，中文：繆思夏工作室
簡介：台灣在地的小型Linux 預裝筆電品牌，特色是針對專業影音創作有特殊的最佳化，筆電有許多客製選項，主要的客戶是Linux 的愛好者與音樂/圖像製作的創作者，合作廠商有喜傑獅、藍天電腦等。
![sleepyMuse](https://user-images.githubusercontent.com/4480740/139666932-2d48acfd-b9c7-45bd-a8f1-e885fd74b80d.jpg)
（圖片License 是: CC-BY-NC-SA 3.0 ）
色彩布局：請參考上面圖片，咖啡色、黃銅的蒸氣龐克風格的用色是我們的主色
官方網站： [https://www.musicha.tw/](https://www.musicha.tw/)
噗浪 ：[https://www.plurk.com/Musichastudio ](https://www.plurk.com/Musichastudio )
臉book粉專： [https://www.facebook.com/musichamusictop/](https://www.facebook.com/musichamusictop/)

**Comment by ycheng** [comment]
pull request to add two links

https://github.com/linux-taiwan/www.linux.org.tw/pull/8

**Comment by kidwm** [comment]
@ycheng 剛剛試了才發現，`github-pages` 用的 `jekyll` 還在舊版，不支援 ruby 3，還是直接裝 `jekyll` 來跑 `jekyll serve`就行了
